---
- name: download docker-compose binary
  shell: curl -L "https://github.com/docker/compose/releases/download/{{version}}/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: apply executable permissions to binary
  file:
    path: /usr/local/bin/docker-compose
    mode: a+x

- name: create site directory if it does not exist
  file:
    path: /home/jake/morganj.co.uk
    state: directory
    mode: "0755"

- name: upload docker-compose file
  copy:
    src: docker-compose.yml
    dest: /home/jake/morganj.co.uk/docker-compose.yml
    owner: root
    group: root
