---
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%wheel"
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"

- name: create the user
  user:
    name: "{{username}}"
    state: present
    groups: wheel

- name: add users ssh key
  authorized_key:
    user: "{{username}}"
    key: "{{ lookup('file', '~/.ssh/{{username}}.pub') }}"
