---
- name: install epel-release
  yum:
    name: epel-release
    state: latest

- name: install nginx
  yum:
    name: nginx
    state: latest
  notify: start nginx

- name: add nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx

- name: add site config
  copy:
    src: jakemorgan.io.conf
    dest: /etc/nginx/conf.d/jakemorgan.io.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
