---
# tasks file for dockerce
- name: install prerequisites
  apt:
    name:
      - apt-transport-https
      - curl
      - ca-certificates
      - software-properties-common
    state: latest

- name: add docker gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: add docker registery to apt sources
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  notify: apt update

- name: install docker
  apt:
    name: docker-ce
    state: latest
